#!/usr/bin/env bash
# Configures a fresh Ubuntu server to serve a custom Nginx header with its hostname

# Ignore SC2154 for Shellcheck
# shellcheck disable=SC2154

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Get the hostname
HOSTNAME=$(hostname)

# Inject custom header into Nginx default config
CONFIG="/etc/nginx/sites-available/default"
if ! grep -q "add_header X-Served-By" "$CONFIG"; then
  sed -i "/^\s*location \/ {/a \        add_header X-Served-By \"$HOSTNAME\";" "$CONFIG"
fi

# Restart Nginx
systemctl restart nginx

