#!/usr/bin/env bash
# configures a server to listening on port 80 of all active servers with IPv4 IP addresses
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
