#!/usr/bin/env bash
# Installs nginx server

# Update package lists non-interactively
apt-get update

# Install Nginx web srver non-interactively
apt-get -y install nginx

# This ensures a GET request to the path returns the required string
echo "Holberton School :)" > /var/www/html/index.html

# Rester Nginx service without using 'systemctl'
service nginx start
