#!/usr/bin/env bash
# Installs nginx server

# Update package lists non-interactively
sudo apt-get update

# Install Nginx web srver non-interactively
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# This ensures a GET request to the path returns the required string
echo "Holberton School for the win! :)" > /var/www/html/index.html

# Define the new location block structure
REDIRECTION_BLOCK="
\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
\t}"

# Use sed to insert the new location block right after 'server_name _;'
sed -i "/server_name _;/a $REDIRECTION_BLOCK" /etc/nginx/sites-enabled/default

# Restart Nginx service without using 'systemctl'
sudo service nginx start
