#!/usr/bin/env bash
# Installs nginx server

# Update package lists non-interactively
sudo apt-get update

# Install Nginx web srver non-interactively
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "This is Igihozo from Holberton School :)" | sudo tee /var/www/html/index.html > /dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/nIgihozo permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service without using 'systemctl'
sudo service nginx start
