#!/usr/bin/env bash
# Installs nginx server

# Update package lists non-interactively
sudo apt-get update

# Install Nginx web srver non-interactively
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# This ensures a GET request to the path returns the required string
echo "Holberton School for the win! :)" > /var/www/html/index.html

# Insert the rewrite rule BEFORE the closing brace of the server block.
sed -i "/}/i \ \ \ \ $REDIRECTION_RULE" /etc/nginx/sites-enabled/default

# Restart Nginx service without using 'systemctl'
sudo service nginx start
