#!/usr/bin/env bash
#Configures Nginx server to have a custom 404 page that contains the string

# Update package lists non-interactively
sudo apt-get update

# Install Nginx web srver non-interactively
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Insert redirect block after server_name
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx service without using 'systemctl'
sudo service nginx start
